### ISSUE TITLE
This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet when using Anchor 0.28.0

### ISSUE THREAD

**Issue by ChewingGlass** [coral-xyz/anchor#2568]
For whatever reason, when using workspace package inheritance with anchor 0.28, I get this error:

```
Caused by:
    This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet
```

This does not happen on Anchor 0.26. 

Can reproduce from https://github.com/helium/helium-program-library

Just `avm use 0.28` and `anchor build`

**Comment by acheroncrypto** [comment]
Thanks for reporting, fixed in #2570.

You can update to latest by running:

```
cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --force
```

**Comment by billythedummy** [comment]
> Thanks for reporting, fixed in #2570.
> 
> You can update to latest by running:
> 
> ```
> cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --force
> ```

I just ran this to update, confirmed that the installed binary is the latest master commit (`Replaced package `anchor-cli v0.28.0 ...` with `anchor-cli v0.28.0 (https://github.com/coral-xyz/anchor#5eb678a8)`). Am still getting the workspace-inheritance error

**Comment by acheroncrypto** [comment]
> Somehow anchor is using `Cargo 1.62.1` even though I have 1.71 installed and a `rust-toolchain.toml` that specifies the toolchain vers
> 
> EDIT: nvm i think its a `cargo-build-bpf` (which is deprecated btw) problem: [solana-labs/solana#31337](https://github.com/solana-labs/solana/issues/31337)

Yes, `1.14` CLI uses `rustc 1.62.0-dev` by default which is before workspace inheritence feature was stabilized in [`1.64`](https://github.com/rust-lang/cargo/pull/10859). It also wouldn't matter whether you use `cargo-build-bpf` or `cargo-build-sbf`. You either need to manually update the build tools yourself or upgrade to `1.16`.
